// Package peer owns the daemon's WireGuard-peer registry. A peer is a
// device (phone, laptop) authorised to connect to the daemon over
// WireGuard; the daemon stores its name, public key, and allowed-IPs
// claim. Private keys for peer-side devices are generated locally at
// Create time and returned to the caller exactly once - the daemon
// retains only the public half.
package peer

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"database/sql"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"net"
	"net/netip"
	"strconv"
	"strings"
	"sync"
	"time"

	"go.jetify.com/typeid"

	"github.com/joshjon/fletcher/internal/errs"
	"github.com/joshjon/fletcher/internal/network/wireguard"
	sqliteq "github.com/joshjon/fletcher/internal/sqlite/gen"
)

// DefaultTunnelCIDR is the WireGuard subnet new peers are allocated
// from when `fletcher peer pair` is used without explicit addressing.
// The .1 address is reserved for the server interface; peer pairing
// hands out .2 through .254.
const DefaultTunnelCIDR = "10.99.0.0/24"

// ErrNotFound is returned when a peer ID does not exist.
var ErrNotFound = errs.New(errs.CategoryNotFound, "peer not found")

// ErrUnauthenticated is returned when an API token matches no peer.
var ErrUnauthenticated = errs.New(errs.CategoryUnauthenticated, "invalid or missing API token")

// ErrNameTaken is returned when CreatePeer would collide on the unique name.
var ErrNameTaken = errs.New(errs.CategoryConflict, "peer name already exists")

// idPrefix is the typeid prefix for peer IDs.
const idPrefix = "peer"

// Peer is the domain shape of a peers row.
type Peer struct {
	ID         string
	Name       string
	PublicKey  wireguard.Key
	AllowedIPs []string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// CreateParams configures a new peer.
type CreateParams struct {
	Name string
	// AllowedIPs are the addresses the daemon will route to this peer
	// (typically a single /32 inside the WireGuard subnet).
	AllowedIPs []string
}

// Created bundles the persisted Peer with the one-time secrets returned to
// the caller. PrivateKey and APIToken are non-empty only on Create - the
// daemon stores only the WireGuard public key and the token's hash.
type Created struct {
	Peer       Peer
	PrivateKey wireguard.Key
	// APIToken is the per-peer bearer token for the daemon's network API.
	// Shown once; only its hash is persisted.
	APIToken string
}

// CreateWithPublicKeyParams configures a peer whose private key was
// generated by the caller. The daemon stores only the public half.
type CreateWithPublicKeyParams struct {
	Name string
	// AllowedIPs are the addresses the daemon will route to this peer
	// (typically a single /32 inside the WireGuard subnet).
	AllowedIPs []string
	// PublicKey is the caller-generated WireGuard public key in
	// wg-quick base64 form. The daemon never sees the private half.
	PublicKey wireguard.Key
}

// CreatedWithPublicKey is the result of CreateWithPublicKey. The
// daemon does not return a private key; the caller already has it.
type CreatedWithPublicKey struct {
	Peer     Peer
	APIToken string
}

// PairingCertProvider supplies the pairing listener's current TLS leaf
// fingerprint (read live so a rotation is reflected immediately) and
// rotates the certificate to track the public endpoint host. The daemon
// wires this to the pairing-cert manager.
type PairingCertProvider interface {
	Fingerprint() string
	SetHost(host string)
}

// Service is the high-level peers API.
type Service struct {
	q                 sqliteq.Querier
	tunnelCIDR        string
	apiEndpoint       string
	remoteAPIEndpoint string

	mu             sync.RWMutex
	publicEndpoint string
	pairingPort    int
	pairingCert    PairingCertProvider

	pending *pendingPairs
}

// Options configures a Service's pair-time defaults.
type Options struct {
	// TunnelCIDR is the subnet `peer pair` allocates /32s from. Empty
	// uses DefaultTunnelCIDR (10.99.0.0/24).
	TunnelCIDR string
	// PublicEndpoint is the host:port (e.g. "home.example.com:51820")
	// that `peer pair` renders into client wg-quick configs. Empty
	// causes PairPeer to fail with a clear error pointing at how to
	// set it; CreatePeer with an explicit server_endpoint still works.
	PublicEndpoint string
	// APIEndpoint is the tunnel-side host:port a paired client dials to
	// drive the daemon's network API (e.g. "10.99.0.1:11700"). Surfaced in
	// pairing output so the client knows where to point.
	APIEndpoint string
	// RemoteAPIEndpoint is the Mode B host:port a client dials to reach the
	// API over a VPN the operator already runs (the daemon's
	// --remote-api-listen, e.g. a Tailscale IP "100.x.y.z:11700"). Empty when
	// Mode B is not configured; surfaced so `peer pair --byo-vpn` can render it.
	RemoteAPIEndpoint string
}

// NewService wires a Service to a sqlc querier with the given options.
func NewService(q sqliteq.Querier, opts Options) *Service {
	cidr := opts.TunnelCIDR
	if cidr == "" {
		cidr = DefaultTunnelCIDR
	}
	return &Service{
		q:                 q,
		tunnelCIDR:        cidr,
		publicEndpoint:    opts.PublicEndpoint,
		apiEndpoint:       opts.APIEndpoint,
		remoteAPIEndpoint: opts.RemoteAPIEndpoint,
		pending:           newPendingPairs(),
	}
}

// APIEndpoint returns the tunnel-side host:port clients dial to drive the
// daemon's network API.
func (s *Service) APIEndpoint() string { return s.apiEndpoint }

// RemoteAPIEndpoint returns the Mode B host:port clients dial to reach the API
// over an operator-run VPN, or "" when Mode B is not configured.
func (s *Service) RemoteAPIEndpoint() string { return s.remoteAPIEndpoint }

// TunnelCIDR returns the subnet used for auto-allocation. The caller
// renders this into the server-side AllowedIPs when needed.
func (s *Service) TunnelCIDR() string { return s.tunnelCIDR }

// PublicEndpoint returns the operator-configured host:port peers should
// dial, or "" if unset. Returned for use in pair-time config rendering.
func (s *Service) PublicEndpoint() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.publicEndpoint
}

// SetPublicEndpoint replaces the public endpoint advertised in pair-time
// configs. Used by the daemon's networking setup when UPnP discovery
// produces an endpoint the operator didn't supply at boot. When a pairing
// cert provider is wired, it also rotates the pairing cert so its SAN
// tracks the new host (iOS rejects a cert whose name does not match the
// dialed host, pin or not). Rotation runs outside the lock - it can mint a
// key - and is best-effort inside the provider.
func (s *Service) SetPublicEndpoint(endpoint string) {
	s.mu.Lock()
	s.publicEndpoint = endpoint
	cert := s.pairingCert
	s.mu.Unlock()
	if cert != nil {
		if host := hostOnly(endpoint); host != "" {
			cert.SetHost(host)
		}
	}
}

// SetPairingCert records the pairing listener's port and cert provider so
// BeginPair starts advertising the pairing endpoint and its live
// fingerprint. The daemon calls this only after the listener binds, so an
// empty advertisement means "no pairing listener", not "try a dead port".
func (s *Service) SetPairingCert(port int, cert PairingCertProvider) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.pairingPort = port
	s.pairingCert = cert
}

// PairingEndpoint returns the public host:port a client dials to call
// CompletePair before the tunnel is up: the public endpoint's host with
// the configured pairing port. Empty when there is no public endpoint or
// no pairing port (so BeginPair advertises nothing and the client falls
// back to whatever it can reach). Tracks UPnP-updated endpoints because
// it derives the host from the live public endpoint.
func (s *Service) PairingEndpoint() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.publicEndpoint == "" || s.pairingPort == 0 {
		return ""
	}
	return net.JoinHostPort(hostOnly(s.publicEndpoint), strconv.Itoa(s.pairingPort))
}

// PairingTLSFingerprint returns the lowercase hex SHA-256 of the leaf the
// pairing listener is currently serving, read live from the cert provider
// so a rotation is reflected immediately. Empty when no pairing endpoint
// is advertised.
func (s *Service) PairingTLSFingerprint() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.publicEndpoint == "" || s.pairingPort == 0 || s.pairingCert == nil {
		return ""
	}
	return s.pairingCert.Fingerprint()
}

// hostOnly returns the host part of a host:port endpoint, or the input
// unchanged when it has no port.
func hostOnly(endpoint string) string {
	if endpoint == "" {
		return ""
	}
	if h, _, err := net.SplitHostPort(endpoint); err == nil {
		return h
	}
	return endpoint
}

// NextAvailableAddress returns the next free /32 inside the service's
// TunnelCIDR, suitable for assigning to a new peer. The .1 host address
// is reserved for the server interface; allocation starts at .2 and
// scans existing peers to skip ones already claimed. Returns a
// CategoryConflict error if the subnet is exhausted.
//
// In-flight BeginPair reservations also count as taken, so a concurrent
// PairPeer call will not duplicate an address an iOS client is about
// to claim with CompletePair.
func (s *Service) NextAvailableAddress(ctx context.Context) (string, error) {
	return s.nextAvailableAddress(ctx, s.pending.addresses())
}

// nextAvailableAddress is NextAvailableAddress with an explicit extra
// set of "already-taken" reservations folded in. BeginPair uses this
// from inside the pending-pairs lock so its read of taken-addresses is
// consistent with the slot it is about to record.
func (s *Service) nextAvailableAddress(ctx context.Context, extraTaken []string) (string, error) {
	prefix, err := netip.ParsePrefix(s.tunnelCIDR)
	if err != nil {
		return "", fmt.Errorf("parse tunnel cidr %q: %w", s.tunnelCIDR, err)
	}
	taken, err := s.takenAddresses(ctx)
	if err != nil {
		return "", err
	}
	for _, raw := range extraTaken {
		raw = strings.TrimSpace(raw)
		if p, perr := netip.ParsePrefix(raw); perr == nil {
			taken[p.Addr()] = true
			continue
		}
		if a, aerr := netip.ParseAddr(raw); aerr == nil {
			taken[a] = true
		}
	}
	server := prefix.Addr().Next()
	candidate := server.Next()
	for prefix.Contains(candidate) && candidate.Next().IsValid() {
		if !taken[candidate] && !candidate.IsMulticast() {
			return candidate.String() + "/32", nil
		}
		candidate = candidate.Next()
	}
	return "", errs.Newf(errs.CategoryConflict, "tunnel subnet %s is exhausted", s.tunnelCIDR)
}

// takenAddresses returns the set of host addresses already claimed by
// existing peers (parsing each peer's AllowedIPs).
func (s *Service) takenAddresses(ctx context.Context) (map[netip.Addr]bool, error) {
	rows, err := s.q.ListPeers(ctx, sqliteq.ListPeersParams{Limit: 1 << 30, Offset: 0})
	if err != nil {
		return nil, fmt.Errorf("list peers for allocation: %w", err)
	}
	taken := make(map[netip.Addr]bool, len(rows))
	for _, r := range rows {
		for _, raw := range strings.Split(r.AllowedIps, ",") {
			raw = strings.TrimSpace(raw)
			if raw == "" {
				continue
			}
			if p, perr := netip.ParsePrefix(raw); perr == nil {
				taken[p.Addr()] = true
				continue
			}
			if a, aerr := netip.ParseAddr(raw); aerr == nil {
				taken[a] = true
			}
		}
	}
	return taken, nil
}

// Create generates a fresh keypair, persists the peer with the public
// half, and returns both halves so the caller can hand the private key
// to the device once.
func (s *Service) Create(ctx context.Context, p CreateParams) (Created, error) {
	if err := p.validate(); err != nil {
		return Created{}, err
	}
	kp, err := wireguard.GenerateKeypair()
	if err != nil {
		return Created{}, err
	}
	row, token, err := s.persistPeer(ctx, p.Name, p.AllowedIPs, kp.Public)
	if err != nil {
		return Created{}, err
	}
	return Created{Peer: row, PrivateKey: kp.Private, APIToken: token}, nil
}

// CreateWithPublicKey persists a peer whose private key was generated by
// the caller (e.g. an iOS client doing client-keygen pairing). The
// daemon stores only the public half and returns the per-peer API
// token; the private key never enters the daemon.
func (s *Service) CreateWithPublicKey(ctx context.Context, p CreateWithPublicKeyParams) (CreatedWithPublicKey, error) {
	if err := wireguard.ValidatePublicKey(p.PublicKey); err != nil {
		return CreatedWithPublicKey{}, errs.Wrap(err, errs.CategoryInvalidArgument)
	}
	base := CreateParams{Name: p.Name, AllowedIPs: p.AllowedIPs}
	if err := base.validate(); err != nil {
		return CreatedWithPublicKey{}, err
	}
	row, token, err := s.persistPeer(ctx, p.Name, p.AllowedIPs, p.PublicKey)
	if err != nil {
		return CreatedWithPublicKey{}, err
	}
	return CreatedWithPublicKey{Peer: row, APIToken: token}, nil
}

// persistPeer is the shared name-check + ID/token mint + DB-insert path
// used by Create and CreateWithPublicKey. The caller has already
// decided on a public key.
func (s *Service) persistPeer(ctx context.Context, name string, allowedIPs []string, pub wireguard.Key) (Peer, string, error) {
	if existing, err := s.q.GetPeerByName(ctx, name); err == nil && existing.ID != "" {
		return Peer{}, "", ErrNameTaken
	} else if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return Peer{}, "", fmt.Errorf("lookup name: %w", err)
	}
	id, err := typeid.WithPrefix(idPrefix)
	if err != nil {
		return Peer{}, "", fmt.Errorf("generate id: %w", err)
	}
	token, err := generateToken()
	if err != nil {
		return Peer{}, "", fmt.Errorf("generate api token: %w", err)
	}
	tokenHash := hashToken(token)
	now := time.Now().Unix()
	row, err := s.q.CreatePeer(ctx, sqliteq.CreatePeerParams{
		ID:           id.String(),
		Name:         name,
		PublicKey:    string(pub),
		AllowedIps:   strings.Join(allowedIPs, ","),
		ApiTokenHash: &tokenHash,
		CreatedAt:    now,
		UpdatedAt:    now,
	})
	if err != nil {
		return Peer{}, "", fmt.Errorf("create peer: %w", err)
	}
	return peerFromRow(row), token, nil
}

// AuthenticateToken returns the peer a bearer token belongs to, or an error if
// the token is empty or matches no peer. Used by the network API's auth layer.
func (s *Service) AuthenticateToken(ctx context.Context, token string) (Peer, error) {
	if token == "" {
		return Peer{}, ErrUnauthenticated
	}
	hash := hashToken(token)
	row, err := s.q.GetPeerByAPITokenHash(ctx, &hash)
	if errors.Is(err, sql.ErrNoRows) {
		return Peer{}, ErrUnauthenticated
	}
	if err != nil {
		return Peer{}, fmt.Errorf("lookup token: %w", err)
	}
	return peerFromRow(row), nil
}

// generateToken returns a 256-bit URL-safe random bearer token.
func generateToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

// hashToken returns the hex SHA-256 of a token; only this is stored.
func hashToken(token string) string {
	sum := sha256.Sum256([]byte(token))
	return hex.EncodeToString(sum[:])
}

// Get returns a peer by ID.
func (s *Service) Get(ctx context.Context, id string) (Peer, error) {
	row, err := s.q.GetPeer(ctx, id)
	if errors.Is(err, sql.ErrNoRows) {
		return Peer{}, ErrNotFound
	}
	if err != nil {
		return Peer{}, fmt.Errorf("get peer: %w", err)
	}
	return peerFromRow(row), nil
}

// List returns peers newest-first.
func (s *Service) List(ctx context.Context, limit, offset int32) ([]Peer, error) {
	if limit <= 0 {
		limit = 50
	}
	rows, err := s.q.ListPeers(ctx, sqliteq.ListPeersParams{
		Limit:  int64(limit),
		Offset: int64(offset),
	})
	if err != nil {
		return nil, fmt.Errorf("list peers: %w", err)
	}
	out := make([]Peer, len(rows))
	for i, r := range rows {
		out[i] = peerFromRow(r)
	}
	return out, nil
}

// Delete removes a peer. Returns false (no error) if the peer was missing.
func (s *Service) Delete(ctx context.Context, id string) (bool, error) {
	n, err := s.q.DeletePeer(ctx, id)
	if err != nil {
		return false, fmt.Errorf("delete peer: %w", err)
	}
	return n > 0, nil
}

func (p CreateParams) validate() error {
	if strings.TrimSpace(p.Name) == "" {
		return errs.New(errs.CategoryInvalidArgument, "name is required")
	}
	if len(p.AllowedIPs) == 0 {
		return errs.New(errs.CategoryInvalidArgument, "at least one allowed_ip is required")
	}
	return nil
}

func peerFromRow(r sqliteq.Peer) Peer {
	allowed := []string{}
	if r.AllowedIps != "" {
		allowed = strings.Split(r.AllowedIps, ",")
	}
	return Peer{
		ID:         r.ID,
		Name:       r.Name,
		PublicKey:  wireguard.Key(r.PublicKey),
		AllowedIPs: allowed,
		CreatedAt:  time.Unix(r.CreatedAt, 0).UTC(),
		UpdatedAt:  time.Unix(r.UpdatedAt, 0).UTC(),
	}
}
