-- AUTO-GENERATED by `make generate` from internal/sqlite/migrations/*.up.sql. DO NOT EDIT.

-- File: 0001_init.up.sql
-- Initialize schema-migrations bookkeeping. Real tables follow in later
-- migrations. This file establishes that version 1 of the schema applied.

-- File: 0002_jobs.up.sql
CREATE TABLE jobs (
    id              TEXT    NOT NULL PRIMARY KEY,
    status          TEXT    NOT NULL CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    trigger_kind    TEXT    NOT NULL CHECK (trigger_kind IN ('ephemeral', 'cron', 'long_running')),
    name            TEXT    NOT NULL,
    command         TEXT    NOT NULL,
    image           TEXT    NOT NULL,
    created_at      INTEGER NOT NULL,
    updated_at      INTEGER NOT NULL,
    started_at      INTEGER,
    completed_at    INTEGER,
    error_message   TEXT,
    exit_code       INTEGER
) STRICT;

CREATE INDEX idx_jobs_status_created_at ON jobs (status, created_at DESC);
CREATE INDEX idx_jobs_created_at        ON jobs (created_at DESC);

-- File: 0003_secrets.up.sql
CREATE TABLE secrets (
    name        TEXT    NOT NULL PRIMARY KEY,
    ciphertext  BLOB    NOT NULL,
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL
) STRICT;

-- File: 0004_pending_approvals.up.sql
CREATE TABLE pending_approvals (
    id              TEXT    NOT NULL PRIMARY KEY,
    status          TEXT    NOT NULL CHECK (status IN ('pending', 'approved', 'denied', 'expired')),
    action          TEXT    NOT NULL,
    justification   TEXT    NOT NULL,
    requester       TEXT    NOT NULL,
    decision_reason TEXT,
    created_at      INTEGER NOT NULL,
    decided_at      INTEGER,
    expires_at      INTEGER NOT NULL
) STRICT;

CREATE INDEX idx_pending_approvals_status_created ON pending_approvals (status, created_at DESC);

-- File: 0005_peers.up.sql
CREATE TABLE peers (
    id          TEXT    NOT NULL PRIMARY KEY,
    name        TEXT    NOT NULL UNIQUE,
    public_key  TEXT    NOT NULL,
    allowed_ips TEXT    NOT NULL,
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL
) STRICT;

CREATE INDEX idx_peers_created_at ON peers (created_at DESC);

-- File: 0006_job_credentials.up.sql
-- Trusted-credential mode (DESIGN.md §5 + Phase 12). The column stores
-- a JSON array of credential names (e.g. ["claude","codex"]); empty
-- string means no credentials are mounted. Storing JSON instead of a
-- separate join table keeps the supervisor's read path one row, which
-- is the only access pattern.
ALTER TABLE jobs ADD COLUMN credentials TEXT NOT NULL DEFAULT '';

-- File: 0007_settings.up.sql
-- Runtime-mutable operational settings, edited via `fletcher settings`.
-- Applied at daemon startup over the flag/env config; changes take effect on
-- the next restart. Bootstrap config (database, socket, age key, listen
-- addresses) stays flag/env only and is not stored here.
CREATE TABLE settings (
    key        TEXT    PRIMARY KEY,
    value      TEXT    NOT NULL,
    updated_at INTEGER NOT NULL
) STRICT;

-- File: 0008_peer_api_token.up.sql
-- Per-peer API token (only the hash is stored) for authenticating the daemon's
-- network-exposed API. Nullable: peers created before this, or without a token,
-- simply cannot use the remote API until re-paired.
ALTER TABLE peers ADD COLUMN api_token_hash TEXT;

-- File: 0009_sessions.up.sql
CREATE TABLE sessions (
    id           TEXT    NOT NULL PRIMARY KEY,
    name         TEXT    NOT NULL UNIQUE,
    image        TEXT    NOT NULL,
    state        TEXT    NOT NULL CHECK (state IN ('running', 'stopped')),
    fork_id      TEXT    NOT NULL,
    fork_path    TEXT    NOT NULL,
    created_at   INTEGER NOT NULL,
    updated_at   INTEGER NOT NULL,
    last_used_at INTEGER
) STRICT;

CREATE INDEX idx_sessions_created_at ON sessions (created_at DESC);

-- File: 0010_job_schedule.up.sql
-- Cron scheduling (DESIGN.md §4: 'cron' is a value of the trigger field, run by
-- the one job engine, not a separate subsystem). A cron job is a definition
-- that rests in the new 'scheduled' status; the supervisor fires it when
-- next_run_at is due by creating a child ephemeral run (parent_id links it back),
-- so each run is a normal job with full history and the runner needs no
-- special-casing. schedule holds the cron expression; next_run_at is the next
-- fire time. parent_id is set on the spawned runs.
--
-- Adding 'scheduled' to the status CHECK requires recreating the table (SQLite
-- cannot ALTER a CHECK constraint). The jobs table has no inbound foreign keys,
-- so a plain recreate is safe.

CREATE TABLE jobs_new (
    id              TEXT    NOT NULL PRIMARY KEY,
    status          TEXT    NOT NULL CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled', 'scheduled')),
    trigger_kind    TEXT    NOT NULL CHECK (trigger_kind IN ('ephemeral', 'cron', 'long_running')),
    name            TEXT    NOT NULL,
    command         TEXT    NOT NULL,
    image           TEXT    NOT NULL,
    created_at      INTEGER NOT NULL,
    updated_at      INTEGER NOT NULL,
    started_at      INTEGER,
    completed_at    INTEGER,
    error_message   TEXT,
    exit_code       INTEGER,
    credentials     TEXT    NOT NULL DEFAULT '',
    schedule        TEXT    NOT NULL DEFAULT '',
    next_run_at     INTEGER,
    parent_id       TEXT
) STRICT;

INSERT INTO jobs_new (
    id, status, trigger_kind, name, command, image, created_at, updated_at,
    started_at, completed_at, error_message, exit_code, credentials,
    schedule, next_run_at, parent_id
)
SELECT
    id, status, trigger_kind, name, command, image, created_at, updated_at,
    started_at, completed_at, error_message, exit_code, credentials,
    '', NULL, NULL
FROM jobs;

DROP TABLE jobs;
ALTER TABLE jobs_new RENAME TO jobs;

CREATE INDEX idx_jobs_status_created_at ON jobs (status, created_at DESC);
CREATE INDEX idx_jobs_created_at        ON jobs (created_at DESC);
CREATE INDEX idx_jobs_parent_id         ON jobs (parent_id);

-- File: 0011_egress_policy.up.sql
-- Per-fork egress policy (DESIGN.md §5): "none" | "allowlist" | "open". Gates
-- the daemon forward-proxy that brokers a fork's outbound network. Default
-- "allowlist" so existing forks keep the curated default; the create path
-- overrides it from the default_egress_policy setting (or an explicit --egress).
ALTER TABLE jobs ADD COLUMN egress_policy TEXT NOT NULL DEFAULT 'allowlist';
ALTER TABLE sessions ADD COLUMN egress_policy TEXT NOT NULL DEFAULT 'allowlist';
