-- AUTO-GENERATED by `make generate` from internal/sqlite/migrations/*.up.sql. DO NOT EDIT.

-- File: 0001_init.up.sql
-- Initialize schema-migrations bookkeeping. Real tables follow in later
-- migrations. This file establishes that version 1 of the schema applied.

-- File: 0002_jobs.up.sql
CREATE TABLE jobs (
    id              TEXT    NOT NULL PRIMARY KEY,
    status          TEXT    NOT NULL CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    trigger_kind    TEXT    NOT NULL CHECK (trigger_kind IN ('ephemeral', 'cron', 'long_running')),
    name            TEXT    NOT NULL,
    command         TEXT    NOT NULL,
    image           TEXT    NOT NULL,
    created_at      INTEGER NOT NULL,
    updated_at      INTEGER NOT NULL,
    started_at      INTEGER,
    completed_at    INTEGER,
    error_message   TEXT,
    exit_code       INTEGER
) STRICT;

CREATE INDEX idx_jobs_status_created_at ON jobs (status, created_at DESC);
CREATE INDEX idx_jobs_created_at        ON jobs (created_at DESC);

-- File: 0003_secrets.up.sql
CREATE TABLE secrets (
    name        TEXT    NOT NULL PRIMARY KEY,
    ciphertext  BLOB    NOT NULL,
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL
) STRICT;

-- File: 0004_pending_approvals.up.sql
CREATE TABLE pending_approvals (
    id              TEXT    NOT NULL PRIMARY KEY,
    status          TEXT    NOT NULL CHECK (status IN ('pending', 'approved', 'denied', 'expired')),
    action          TEXT    NOT NULL,
    justification   TEXT    NOT NULL,
    requester       TEXT    NOT NULL,
    decision_reason TEXT,
    created_at      INTEGER NOT NULL,
    decided_at      INTEGER,
    expires_at      INTEGER NOT NULL
) STRICT;

CREATE INDEX idx_pending_approvals_status_created ON pending_approvals (status, created_at DESC);

-- File: 0005_peers.up.sql
CREATE TABLE peers (
    id          TEXT    NOT NULL PRIMARY KEY,
    name        TEXT    NOT NULL UNIQUE,
    public_key  TEXT    NOT NULL,
    allowed_ips TEXT    NOT NULL,
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL
) STRICT;

CREATE INDEX idx_peers_created_at ON peers (created_at DESC);
